Repository shinhan-7hillguys/7hillguys-back, pull requests merged in 2025-03, with the labels that each got.

#14 Update .gitignore .dsStore
  .gitignore
Labels: fixed

#24 파일 부족으로 인한 임시 주석처리입니다.
  src/main/java/com/shinhan/peoch/invest/controller/InvestmentResultController.java
Labels: bug, fixed

#30 feature/investReview
  src/main/java/com/shinhan/peoch/auth/controller/AuthController.java
  src/main/java/com/shinhan/peoch/config/SecurityConfig.java
  src/main/java/com/shinhan/peoch/security/jwt/JwtUtil.java
Labels: fixed

#35 엑시트 기능 구현
  src/main/java/com/shinhan/peoch/invest/service/UserProfileService.java
  src/main/java/com/shinhan/peoch/lifecycleincome/DTO/ExitResponseDTO.java
  src/main/java/com/shinhan/peoch/lifecycleincome/controller/InvestmentController.java
  src/main/java/com/shinhan/peoch/lifecycleincome/service/ExitCostService.java
  src/main/java/com/shinhan/peoch/lifecycleincome/service/InvestmentService.java
  src/main/java/com/shinhan/peoch/lifecycleincome/service/SetInvestAmountService.java
  src/main/java/com/shinhan/repository/ExpectedIncomeRepository.java
  src/main/java/com/shinhan/repository/InvestmentRepository.java
  src/main/java/com/shinhan/repository/UserProfileRepository.java
Labels: enhancement

#36 Feature/25 exit
  src/main/java/com/shinhan/peoch/lifecycleincome/service/ExpectedValueService.java
  src/main/java/com/shinhan/peoch/lifecycleincome/service/InvestmentService.java
Labels: enhancement

#45 Feature/25 exit
  src/main/java/com/shinhan/peoch/lifecycleincome/DTO/ApiResponseDTO.java
  src/main/java/com/shinhan/peoch/lifecycleincome/DTO/SetAmountRequestDTO.java
  src/main/java/com/shinhan/peoch/lifecycleincome/controller/InvestmentController.java
  src/main/java/com/shinhan/peoch/lifecycleincome/service/ExitCostService.java
  src/main/java/com/shinhan/peoch/lifecycleincome/service/InvestmentService.java
  src/main/java/com/shinhan/peoch/lifecycleincome/service/SetInvestAmountService.java
  src/main/java/com/shinhan/repository/PaymentRepository.java
  src/test/java/com/shinhan/peoch/MyTest.java
  src/test/java/com/shinhan/peoch/PeochApplicationTests.java
  src/test/java/com/shinhan/peoch/TestPeochApplication.java
  src/test/java/com/shinhan/peoch/TestcontainersConfiguration.java
  src/test/java/com/shinhan/peoch/invest/InvestmentServiceTest.java
  src/test/java/com/shinhan/peoch/invest/NgrokApiRequestTest.java
  src/test/java/com/shinhan/peoch/invest/NormalizeTest.java
  src/test/java/com/shinhan/peoch/invest/NormalizeTest2.java
Labels: enhancement
